name: dnlp2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch=2.0
  - torchvision=0.15
  - torchaudio=2.0
  - pytorch-cuda=11.8
  - pip
  - pip:
      - cmake
      - lit
      - tqdm>=4.66
      - requests
      - importlib-metadata
      - filelock>=3.12
      - scikit-learn>=1.3
      - tokenizers>=0.13
      - explainaboard_client>=0.1
      - tensorboard>=2.14
      - torch_tb_profiler>=0.4
      - pytorch_optimizer>=2.11
      - spacy[cuda-autodetect]>=3.5
      - spacy-lookups-data>=1.0
      - pre-commit
      - ray[tune]>=2.6
      - optuna>=3.3